# Generated by Django 5.2.11 on 2026-02-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='radio_impacto',
            field=models.FloatField(blank=True, default=0.0, help_text='Radio de impacto en metros', null=True),
        ),
    ]
