# Generated by Django 5.2.11 on 2026-02-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='provider',
            field=models.CharField(blank=True, help_text='Proveedor usado para el envío (mailersend_api, smtp, simulate)', max_length=50),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='provider_id',
            field=models.CharField(blank=True, help_text='ID de mensaje devuelto por el proveedor', max_length=255),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='provider_response',
            field=models.TextField(blank=True, help_text='Respuesta cruda del proveedor (JSON o texto)'),
        ),
    ]
